#!/bin/bash
echo "expected output='total_obs_sum=1867.634357371268'"
python optimization_spinalCtrl.py -c test_data/rfx_checkpoint.pkl --duration=0.1 --repeat=2 --seed=64 --debug --test | grep 'total_obs_sum' | awk -F ' ' '{print $6}'

